language: ruby
rvm:
- 2.6.6
branches:
  only:
   - master
   - staging
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - sshpass
services:
  - postgresql
install:
- bundle update --bundler
- bundle install --jobs=3 --retry=3
before_script:
  - psql -c 'create database dfb_test;' -U postgres
script:
- bin/rails test
deploy:
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/travis-swb-deploy.sh
