language: ruby
rvm:
- 2.2.7
branches:
  only:
   - master
   - staging
addons:
  apt:
    packages:
    - sshpass
install:
- bundle install --jobs=3 --retry=3
script:
- bin/rails test
deploy:
  #deploy to staging
  provider: script
  script: travis-webfaction-deploy.sh staging
  on:
    branch: staging
    
