language: ruby
rvm:
- 2.2.7
branches:
  only:
   - master
   - staging
addons:
  postgresql: "9.4"
  apt:
    packages:
    - sshpass
services:
  - postgresql
install:
- bundle install --jobs=3 --retry=3
before_script:
  - psql -c 'create database dfb_test;' -U postgres
script:
- bin/rails test
# deploy:
#   #deploy to production
#   - provider: script
#     script: bash $TRAVIS_BUILD_DIR/travis-webfaction-deploy.sh production
#     on:
#      branch: master
#   #deploy to staging
#   - provider: script
#     script: bash $TRAVIS_BUILD_DIR/travis-webfaction-deploy.sh staging
#     on:
#       branch: staging
