language: ruby
rvm:
- 2.2.7
branches:
  only:
   - master
   - staging
addons:
  apt:
    packages:
    - sshpass
install:
- bundle install --jobs=3 --retry=3
script:
- bin/rails test
after_success:
- export SSHPASS=$DEPLOY_PASS
- sshpass -e ssh -o stricthostkeychecking=no ${DEPLOY_USER}@${DEPLOY_HOST} bash "${DEPLOY_HOME}/git_deploy.sh"
  "${DEPLOY_PATH}" ${DEPLOY_REPO} ${DEPLOY_BRANCH}
- sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST bash "${DEPLOY_PATH}/deploy.sh"
