FROM phusion/passenger-ruby26

ENV HOME /root

CMD ["/sbin/my_init"]

RUN mkdir /usr/src/app
RUN mkdir /usr/src/scripts

RUN apt update -q && apt install -yq imagemagick default-jre nodejs npm default-jre
RUN npm install --global yarn
RUN gem install bundler -v 1.17.3

RUN rm -f /etc/service/nginx/down
RUN rm /etc/nginx/sites-enabled/default
COPY webapp.conf /etc/nginx/sites-enabled/webapp.conf

WORKDIR /usr/src/app

EXPOSE 80

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
