default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
    <<: *default
    host: db
    database: dfb_development
    username: postgres
    password: <%= ENV['DFB_DB_PASS'] %>

test:
    <<: *default
    host: db
    database: dfb_test
    username: postgres
    password: <%= ENV['DFB_DB_PASS'] %>

staging:
    <<: *default
    port:     <%= ENV['DFB_DB_PORT'] %>
    host:     <%= ENV['DFB_DB_HOST'] %>
    database: <%= ENV['DFB_DB_NAME'] %>
    username: <%= ENV['DFB_DB_USER'] %>
    password: <%= ENV['DFB_DB_PASS'] %>

production:
    <<: *default
    port:     <%= ENV['DFB_DB_PORT'] %>
    host:     <%= ENV['DFB_DB_HOST'] %>
    database: <%= ENV['DFB_DB_NAME'] %>
    username: <%= ENV['DFB_DB_USER'] %>
    password: <%= ENV['DFB_DB_PASS'] %>
