default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
    <<: *default
    database: dfb_development
    username: postgres

test:
    <<: *default
    database: dfb_test
    username: postgres

staging:
    <<: *default
    database: <%= ENV['DFB_DB_STAGING'] =>
    username: <%= ENV['DFB_DB_USER_STAGING'] =>
    password: <%= ENV['DFB_DB_PASS_STAGING'] =>

production:
    <<: *default
    database: <%= ENV['DFB_DB_PRODUCTION'] =>
    username: <%= ENV['DFB_DB_USER_PRODUCTION'] =>
    password: <%= ENV['DFB_DB_PASS_PRODUCTION'] =>
