development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: dfb_development
  pool: 5
  timeout: 5000
  username: postgres

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: dfb_test
  pool: 5
  timeout: 5000
  username: postgres

# production:
#   <<: *default
#   database: db/production.sqlite3
