name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dfb_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt -yqq install libpq-dev build-essential libcurl4-openssl-dev zlib1g-dev default-jre imagemagick file
          bundle install --jobs 4 --retry 3
      - name: Build and run tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          DATABASE_URL: postgres://postgres:@localhost:5432/dfb_test
          RAILS_ENV: test
          RAILS_MASTER_KEY: $
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
          rails test -v